export const SET_NAVIGATION_VISIBLE = 'SET_NAVIGATION_VISIBLE'

export const SET_PREVIEW_VISIBLE = 'SET_PREVIEW_VISIBLE'

export const SET_TOOLBAR_STYLE = 'SET_TOOLBAR_STYLE'

export const SET_SITES = 'SET_SITES'
export const SET_CURRENT_SITE_ID = 'SET_CURRENT_SITE_ID'
export const SET_SITE_FILES = 'SET_SITE_FILES'
