export const SET_MESSAGE = 'SET_MESSAGE'

export const SET_NAVIGATION_VISIBLE = 'SET_NAVIGATION_VISIBLE'

export const SET_PREVIEW_VISIBLE = 'SET_PREVIEW_VISIBLE'

export const SET_TOOLBAR_STYLE = 'SET_TOOLBAR_STYLE'
export const SET_DARK_MODE = 'SET_DARK_MODE'

export const SET_SITES = 'SET_SITES'

export const SET_EDITOR_ITEM = 'SET_EDITOR_ITEM'
export const SET_EDITOR_CONTENT = 'SET_EDITOR_CONTENT'
export const SET_EDITOR_SCROLL_FRACTION = 'SET_EDITOR_SCROLL_FRACTION'

export const SET_AUTHOR_NAME = 'SET_AUTHOR_NAME'
